---
- hosts: masters
  vars_files:
    - vars.yaml
  tasks:
      - name: Apache Package uninstallation
        yum:
          name: "{{ item }}"
          state: present
        when: item not in ["firewalld", "python3-firewall"]
        loop:  "{{ packages }}"

      - name: Remove configuration setting
        file:
          dest: /etc/httpd/conf.d/webserver.conf
          state: absent

      - name: Remove Website code
        file: 
          dest: "/var/www/html/{{ item }}"
          state: absent
        loop: "{{ code_location }}"

      - name: Disable firewall services for httpd
        firewalld:
          port: "{{ item }}"
          permanent: no
          state: disabled
          immediate: no
        loop: "{{ firewall_settings }}"

      - name: "Remove /tmp/infodir/httpd"
        file:
          name: /tmp/infodir/httpd
          state: absent


...


