
---
- name: "Destroy nginx server"
  hosts: master
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: no
  tags:
    - destroy_nginx_server
    - destroy_nginx
    - destroy

  vars_files:
    - vars.yaml
  
  tasks:
      - name: Nginx Package uninstallation
        yum:
          name: "{{ item }}"
          state: absent
        when: item not in ["firewalld", "python3-firewall"]
        loop:  "{{ packages }}"

      - name: Remove configuration setting
        file:
            state: absent
            name: /etc/nginx/conf.d/webserver.conf

      - name: Remove Website code
        file:
          dest: "/var/www/html/{{ item }}"
          state: absent
        loop: "{{ code_location }}"

      - name: Disable firewall services for nginx
        firewalld:
          port: "{{ item }}"
          permanent: no
          state: disabled
          immediate: no
        loop: "{{ firewall_settings }}"

      - name: "Remove /tmp/infodir/nginx"
        file:
          name: /tmp/infodir/nginx
          state: absent

...
