# This playbook contains some examples related editing a file using blockinfile module
---
- hosts: localhost
  gather_facts: yes
  tasks:

    - name: Check disk name and size
      set_fact:
          disk_name: "{{ disk_name | default([]) + [item+'-'+ansible_devices[item].size] }}" 
      loop: "{{ ansible_devices.keys()|list }}"
      when: ansible_devices[item].vendor == 'ATA'


    - name: System details
      shell: |
        echo -e "
        ===============================================
        Linux Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}
        ===============================================
        System Uptime: $(uptime -p)
        ===============================================
        System Architecture: {{ ansible_architecture }}
        ===============================================
        Hostname(FQDN): {{ ansible_fqdn }}
        ===============================================
        Hard-Disk Name: {{ disk_name }}
        ===============================================
        Total RAM: {{ ansible_memory_mb.real.total }}
        ===============================================
        Total Swap: {{ ansible_memory_mb.swap.total }}
        ===============================================
        Total CPU: {{ ansible_processor_cores }} 
        ===============================================
        IP address: {{ ansible_all_ipv4_addresses }}
        ===============================================
        Default IP address: {{ ansible_default_ipv4['address'] }}
        ===============================================
          " > /tmp/sysinfo
      args:
        executable: /bin/bash
...
