---
- hosts: master
  tasks:
    - name: Capture IPV4 address
      shell: "hostname -I | cut -d ' ' -f 2"
      register: ipv4

    - name: Save the IP address
      set_fact:
        server_ip: "{{ ipv4.stdout }}"

- hosts: workers
  tasks:
    - name: Put SELinux in permissive mode
      selinux:
        policy: targeted
        state: permissive

    - name: Install nfs client package
      yum:
        name: nfs-utils
        state: present

    - name: "show all nfs-shares"
      shell: "showmount -e {{ hostvars['master']['server_ip'] }}"
      register: share_output

    - name: "Display all nfs-shares"
      debug:
        msg: "{{ share_output.stdout }}"

    - name: mount nfs folder
      mount:
        src: "{{ hostvars['master']['server_ip'] }}:/details"
        path: /mnt/nfs
        state: mounted
        fstype: nfs
        opts: rw,sync
...

