---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  tasks:
    - name: Install firewall dependent package
      yum:
        name: python3-firewall
        state: present

    - name: Permit traffic in default zone on port 8081/tcp
      firewalld:
        port: 8081/tcp
        permanent: yes
        state: enabled
        immediate: yes
...
