Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel8"
  config.vm.network "private_network", ip: "172.18.0.21"
  # config.vm.network "public_network"
   config.vm.provision "shell", inline: <<-SHELL
     sudo hostnamectl set-hostname worker1
     sudo echo -e "redhat\nredhat" | sudo  passwd root
     sudo echo -e "\n172.18.0.20   master\n172.18.0.21   worker1\n" >> /etc/hosts

     sudo sed -i "s/#PasswordAuthentication yes/PasswordAuthentication yes/g" /etc/ssh/sshd_config 
     sudo sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config 
     sudo sed -i "s/#PermitRootLogin yes/PermitRootLogin yes/g" /etc/ssh/sshd_config 
     sudo sed -i "s/PermitRootLogin no/PermitRootLogin yes/g" /etc/ssh/sshd_config 
     sudo sed -i 's/old-text/new-text/g' /etc/ssh/ssh_config
     sudo sed -i "s/#   StrictHostKeyChecking ask/StrictHostKeyChecking no/g" /etc/ssh/ssh_config

     sudo systemctl restart sshd
     sudo subscription-manager register --username kripa-koth --password kripakoth@12345 --auto-attach
     sudo yum install git ansible vim rsync wget -y
   SHELL
end
