Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
   config.vm.network "public_network"
   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     sudo hostnamectl set-hostname worker
     sudo echo -e "redhat\nredhat" | sudo  passwd root
     sudo echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
     sudo echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
     sudo systemctl restart sshd
     sudo apt update
     sudo apt install openjdk-8-jdk -y
     sudo apt install openjdk-11-jdk -y
     sudo apt install git -y

   SHELL
end
