---
- hosts: masters
  gather_facts: false
  become: true
  vars:
    mysql_root_password: 'redhat'
    packages:
      - mysql-server
      - mysql-devel
      - python39
      - python39-devel
      - python39-pip
      - gcc
      - python3-firewall
    ansible_python_interpreter: /usr/bin/python3.6

  tasks:
    - block:
        - name: Package installation
          dnf:
            name: "{{ item }}"
            state: present
          loop: 
            - "{{ packages }}"

        - name: Install Required pip modules
          pip:
            name: PyMySQL
            state: present
            executable: pip3

        - name: Restart service
          service:
            name: mysqld
            state: started
            enabled: yes

        - name: Ensure root user can only login from localhost
          mysql_user:
            login_password: "{{ mysql_root_password }}"
            check_implicit_admin: yes
            name: root
            host: "{{ item }}"
            password: "{{ mysql_root_password }}"
            state: present
          with_items:
            - localhost
            - 127.0.0.1

        - name: Enable firewall services for httpd
          firewalld:
            port: "{{ item }}"
            permanent: yes
            state: enabled
          loop:
            - "{{ firewall_settings }}"

      rescue:
        - name: Uninstall mysql package
          dnf:
            name: "{{ item }}"
            state: absent
          loop: 
            - mysql-server
            - mysql-devel

        - name: Remove mysql settings
          file:
            name: "/var/lib/mysql"
            state: absent


  handlers:   
    - name: restart_me
      service:
        name: mysqld
        state: reloaded
...


