---
- hosts: masters
  gather_facts: false
  become: true
  vars:
    mysql_root_password: 'redhat'
    packages:
      - mysql-server
      - mysql-devel
      - python39
      - python39-devel
      - python39-pip
      - gcc
      - python3-firewall
    ansible_python_interpreter: /usr/bin/python3.6
    conf_settings:
      conf/webserver1.conf: website1
      conf/webserver2.conf: website2
      conf/webserver3.conf: website3

  tasks:
    - name: Package installation
      dnf:
        name: "{{ item }}"
        state: present
      loop: 
        - "{{ packages }}"

    - name: Configuration setting
      template:
        src: webserver.j2
        dest: /etc/httpd/conf.d/
      notify: 
        - restart_me

    - name: Copy Website code
      copy: 
        src: "{{ item.0 }}"
        dest: "/var/www/html/{{ item.1 }}"
      loop:
        - "{{ code_location }}"
      notify: 
        - restart_me

    - name: Restart service
      service:
        name: httpd
        state: started

    - name: Enable firewall services for httpd
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - "{{ firewall_settings }}"

    - name: Testing website 1
      command: "{{ item }}"
      loop:
        - "curl http://master"
        - "curl http://master:6800"
        - "curl http://master:5800"

  handlers:   
    - name: restart_me
      service:
        name: httpd
        state: reloaded
...


