Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  # using a specific IP.
  config.vm.network "private_network", ip: "172.24.0.9"

  # config.vm.network "public_network"

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
   end
   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y ansible
     sudo hostnamectl set-hostname master 
     sudo echo -e "redhat\nredhat" | sudo  passwd root
     sudo echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
     sudo echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
     sudo systemctl restart sshd
     sudo git clone https://github.com/lavatech321/DevOps_Projects.git /tmp/project
     sudo ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
     sudo echo -e "\n172.24.0.9   master\n172.24.0.10   worker1\n" >> /etc/hosts
     sudo apt-get install expect -y
     sudo expect /tmp/project/vagrant/passwordless
   SHELL
end
