# This playbook contains some examples related to file and directory
---
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Create empty directory
      file:
        path: /etc/foo
        state: directory
        owner: root
        group: root
        mode: '0777'
        # Change ownership recursively
        recurse: yes

    - name: Create empty file
      file:
        path: /etc/foo.conf
        state: touch
        mode: u=rw,g=r,o=r
        owner: root
        group: root

    - name: Create a symbolic link
      file:
        src: /etc/ssh/sshd_config
        dest: /sshd.conf
        owner: root
        group: root
        state: link

    - name: Create a hard link
      file:
        src: /etc/ssh/sshd_config
        dest: /sshd.conf
        owner: root
        group: root
        state: link

    - name: Delete file/folder
      file:
        name: /etc/foo
        state: absent

    - name: Update modification and access time of given file
      file:
        path: /etc/foo.conf
        state: file
        modification_time: now
        access_time: now

    - name: Download file from url
      get_url:
        url: https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user
        dest: /VSCodeUserSetup-x64-1.71.0.exe
        mode: '0440'


...
