---
- hosts: master
  tasks:
    - name: Capture IPV4 address
      shell: "hostname -I | cut -d ' ' -f 2"
      register: ipv4

    - name: Save the IP address
      set_fact:
        server_ip: "{{ ipv4.stdout }}"

- hosts: worker
  vars:
    package_list:
      - cifs-utils
  tasks:
    - name: installing packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ package_list }}"

    - name: create a directory to mount samba share
      file:
        path: /mount_samba
        state: directory
        owner: root
        group: root
        mode: '777'

    - name: Mount network share
      mount:
        src: "//{{ hostvars['master']['server_ip'] }}/tester"
        path: /mount_samba
        fstype: cifs
        opts: 'username=rohit,password=r@12345'
        state: mounted
...

