---
- hosts: "masters, workers"
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: no

  tasks:
     - name: install and configure dependencies
       apt_key:
         url:  https://pkg.jenkins.io/debian-stable/jenkins.io.key
         state: present

     - name: Add jenkins repository
       apt_repository:
         repo: "deb http://pkg.jenkins.io/debian-stable binary/"
         state: present

     - name: Install Openjdk
       apt:
         name: "openjdk-11-jdk"
         state: present
         update_cache: yes


- hosts: "masters"
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: no

  tasks:
     - name: Install Jenkins
       apt:
         name: "jenkins"
         state: present
         update_cache: yes
...
