---
- hosts: localhost
  vars:
    list:
      - mariadb
      - mariadb-server
      - python39
      - python39-devel
      - python39-pip
      - gcc
      - python3-firewall
    ansible_python_interpreter: /usr/bin/python3.6
    mysql_root_password: redhat
  tasks:
    - block:
        - name: "Install mariadb"
          yum:
            name: "{{list}}"
            state: latest

        - name: Install Required pip modules
          pip:
            name: PyMySQL
            state: present
            executable: pip3

        - name: "Start service"
          service:
            name: mariadb
            state: started
          register: service_start


        - name: Ensure root user can only login from localhost
          mysql_user:
            login_password: redhat
            check_implicit_admin: yes
            name: root
            host: "{{ item }}"
            password: redhat
            state: present
          with_items:
            - localhost
            - 127.0.0.1
          when: service_start.changed


        - name: Add .my.cnf to user home
          template:
            src: my.cnf.j2
            dest: /root/.my.cnf

        - name: Reload privilege tables
          command: |
            mysql -p{{ mysql_root_password }} -ne "{{ item }}"
          with_items:
            - FLUSH PRIVILEGES
          changed_when: False

        - name: Remove anonymous users
          command: |
            mysql -p{{ mysql_root_password }} -ne "{{ item }}"
          with_items:
            - DELETE FROM mysql.user WHERE User=''
          changed_when: False

        - name: Disallow root login remotely
          command: |
            mysql -p{{ mysql_root_password }} -ne "{{ item }}"
          with_items:
            - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
          changed_when: False

        - name: Remove test database and access to it
          command: |
            mysql -p{{ mysql_root_password }} -ne "{{ item }}"
          with_items:
            - DROP DATABASE IF EXISTS test
            - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
          changed_when: False

        - name: Reload privilege tables
          command: |
            mysql -p{{ mysql_root_password }} -ne "{{ item }}"
          with_items:
            - FLUSH PRIVILEGES
          changed_when: False

        - name: Delete .my.conf
          file:
            path: /root/.my.cnf
            state: absent

        - name: Put SELinux in permissive mode
          selinux:
            policy: targeted
            state: permissive

        - name: create wordpress database
          mysql_db:
            name: wordpress
            state: present
            login_user: root
            login_password: redhat

        - name: Create customer database
          shell: mysql -uroot -predhat -e "create database customer"
          when: service_start.changed

        - name: Create info table inside customer database
          shell: mysql -uroot -predhat -e "create table customer.info(fname varchar(20), lname varchar(20))"
          when: service_start.changed

        - name: Insert details into customer.info table -
          shell: mysql -uroot -predhat -e "insert into customer.info values('raj','sharma')"
          when: service_start.changed

        - name: Allow root access from anywhere
          shell: mysql -uroot -predhat -e "CREATE USER 'root'@'%' IDENTIFIED BY 'redhat'; GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';FLUSH PRIVILEGES;"
          when: service_start.changed

      rescue:
        - name: Remove Packages
          yum:
            name: "{{list}}"
            state: absent
        - file:
            name: "/var/lib/mysql"
            state: absent

...
