---
- hosts: masters
  tasks:
    - name: Capture IPV4 address
      shell: "hostname -I | cut -d ' ' -f 2"
      register: ipv4

    - name: Save the IP address
      set_fact:
        server_ip: "{{ ipv4.stdout }}"

    - name: Package installation
      yum:
        name: nfs-utils
        state: present

    - name: Configuration setting
      copy:
        src: exports
        dest: /etc/exports
      notify: 
        - restart_me

    - name: Firewall setting
      command: "firewall-cmd --permanent --add-service=nfs"
      
    - name: Firewall setting
      command: "firewall-cmd --reload"

    - name: Restart service
      service:
        name: nfs-server
        state: started

  handlers:   
    - name: restart_me
      service:
        name: nfs-server
        state: reloaded
...

