---
- hosts: masters
  vars:
    folder_ips:
      /details: worker1
    ansible_python_interpreter: /usr/bin/python3.6
  tasks:

    - name: Capture IPV4 address
      shell: "hostname -I | cut -d ' ' -f 2"
      register: ipv4

    - name: Save the IP address
      set_fact:
        server_ip: "{{ ipv4.stdout }}"

    - name: Package installation
      yum:
        name: nfs-utils
        state: present

    - name: Create nfs share folder
      file: 
        name: /details
        state: directory
        mode: 0777

    - name: Configuration setting
      template:
        src: exports.j2
        dest: /etc/exports
      notify: 
        - restart_me

    - name: Install firewall dependent package
      yum:
        name: python3-firewall
        state: present

    - name: Permit nfs traffic in firewall
      firewalld:
        service: nfs
        permanent: yes
        state: enabled


    - name: Permit rpc-bind traffic in firewall
      firewalld:
        service: rpc-bind
        permanent: yes
        state: enabled
    - name: Permit mountd traffic in firewall
      firewalld:
        service: nfs
        permanent: yes
        state: enabled

    - name: Restart service
      service:
        name: nfs-server
        state: started

  handlers:   
    - name: restart_me
      service:
        name: nfs-server
        state: reloaded
...

