---
- hosts: workers
  tasks:
    - name: mount nfs folder
      Mount:
       src: ansible_hosts
        src: "{{ hostvars['masters']['server_ip'] }}/root/project"
        path: /mnt
        state: mounted
        fstype: nfs
...

