Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", ip: "172.18.0.12"
  # config.vm.network "public_network"
   config.vm.provision "shell", inline: <<-SHELL
     sudo hostnamectl set-hostname worker1
     sudo echo -e "redhat\nredhat" | sudo  passwd root
     sudo echo -e "\n172.18.0.11   master\n172.18.0.12   worker1\n" >> /etc/hosts
     sudo echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
     sudo echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
     sudo systemctl restart sshd
     sudo apt update
     sudo apt install git ansible -y
   SHELL
end
