# Sample example on creating a new partition
---
- hosts: localhost
  vars_files:
    - sample_vars.yaml
  tasks:

    ####### Checking the name of device ########
    - name: Check disk name and size
      set_fact:
          disk_name: "{{ disk_name | default([]) + [item] }}"
      loop: "{{ ansible_devices.keys()|list }}"
      when: ansible_devices[item].vendor == 'ATA'

    ##### Creating Partition #####
    - name: Create a new ext4 primary partition
      parted:
        device: /dev/sdb
        number: 2
        state: present
        part_end: 500MB
        unit: MB
        label: gpt
      when: "'sdb' in disk_name"
      register: partition_info

    - name: display
      debug:
        msg: "{{ partition_info }}"

    - name: fs format
      filesystem:
        fstype: xfs
        dev: "/dev/sdb1"

    - name: Create mount directory
      file:
        name: /mnt/project
        state: directory

    - name: Mount /dev/sdb1 partition
      mount:
        path: /mnt/project
        src: /dev/sdb1
        fstype: xfs
        state: mounted

...
