---
- hosts: localhost
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: no
  vars_files:
    - vars.yaml

  tasks:
       - name: Package Uninstallation
         dnf:
           name: "{{ item }}"
           state: absent
         when: item not in ["firewalld", "python3-firewall", "yum-utils"]
         loop:
           - "{{ packages }}"

       - name: "Remove /tmp/infodir/terraform"
         file:
            name: /tmp/infodir/terraform
            state: absent

